/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dtosimples.telas;

/**
 *
 * @author GHT
 */
public class Controle extends javax.swing.JFrame {

    /**
     * Creates new form Controle
     */
    public Controle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCompra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtVenda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIcms = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLucro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtGarantia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTamanho = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnBuscarID = new javax.swing.JButton();
        btnBuscarNome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("ID Produto");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 90, 42);

        txtID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtID);
        txtID.setBounds(160, 40, 90, 22);

        jLabel2.setText("Nome Produto");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 90, 90, 42);

        txtNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtNome);
        txtNome.setBounds(170, 100, 71, 22);

        jLabel3.setText("Modelo Produto");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 150, 110, 42);

        txtModelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtModelo);
        txtModelo.setBounds(180, 160, 71, 22);

        jLabel4.setText("Cor Produto");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 210, 110, 42);

        txtCor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtCor);
        txtCor.setBounds(180, 210, 71, 22);

        jLabel5.setText("Fabricante Prod.");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 260, 110, 42);

        txtFabricante.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtFabricante);
        txtFabricante.setBounds(180, 270, 71, 22);

        jLabel6.setText("Valor Compra");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 320, 110, 42);

        txtCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtCompra);
        txtCompra.setBounds(180, 330, 71, 22);

        jLabel7.setText("Valor Venda");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel7);
        jLabel7.setBounds(430, 30, 90, 42);

        txtVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtVenda);
        txtVenda.setBounds(550, 30, 71, 22);

        jLabel8.setText("ICMS");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 80, 70, 42);

        txtIcms.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtIcms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIcmsActionPerformed(evt);
            }
        });
        getContentPane().add(txtIcms);
        txtIcms.setBounds(550, 80, 71, 22);

        jLabel9.setText("Lucro");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel9);
        jLabel9.setBounds(430, 140, 70, 42);

        txtLucro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtLucro);
        txtLucro.setBounds(550, 130, 71, 22);

        jLabel10.setText("Estoque");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 190, 70, 42);

        txtEstoque.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtEstoque);
        txtEstoque.setBounds(550, 180, 71, 22);

        jLabel11.setText("Garantia");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel11);
        jLabel11.setBounds(430, 240, 70, 42);

        txtGarantia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtGarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGarantiaActionPerformed(evt);
            }
        });
        getContentPane().add(txtGarantia);
        txtGarantia.setBounds(540, 240, 71, 22);

        jLabel12.setText("Tamanho");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel12);
        jLabel12.setBounds(430, 290, 70, 42);

        txtTamanho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtTamanho);
        txtTamanho.setBounds(550, 300, 71, 22);

        btnSalvar.setText("Salvar");
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(80, 410, 72, 23);

        btnAlterar.setText("Alterar");
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(240, 410, 72, 23);

        btnExcluir.setText("Excluir");
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(400, 410, 75, 23);

        btnBuscarID.setText("BuscarID");
        btnBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIDActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarID);
        btnBuscarID.setBounds(260, 40, 100, 23);

        btnBuscarNome.setText("BuscarNome");
        getContentPane().add(btnBuscarNome);
        btnBuscarNome.setBounds(260, 100, 100, 23);

        setBounds(0, 0, 701, 498);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIcmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIcmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIcmsActionPerformed

    private void txtGarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGarantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGarantiaActionPerformed

    private void btnBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscarID;
    private javax.swing.JButton btnBuscarNome;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCompra;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIcms;
    private javax.swing.JTextField txtLucro;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTamanho;
    private javax.swing.JTextField txtVenda;
    // End of variables declaration//GEN-END:variables
}
