/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dtosimples.telas;
import com.mycompany.dtosimples.crud.Crud;
import com.mycompany.dtosimples.entities.Calcado;

/**
 *
 * @author GHT
 */
public class Controle extends javax.swing.JFrame {

    /**
     * Creates new form Controle
     */
    public Controle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCompra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtVenda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIcms = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLucro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtGarantia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTamanho = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnBuscarID = new javax.swing.JButton();
        btnBuscarNome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID Produto");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 120, 42);

        txtID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtID);
        txtID.setBounds(150, 20, 70, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nome Produto");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 120, 42);

        txtNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(150, 70, 100, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Modelo Produto");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 120, 42);

        txtModelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtModelo);
        txtModelo.setBounds(150, 120, 100, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Cor Produto");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 120, 42);

        txtCor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtCor);
        txtCor.setBounds(150, 170, 100, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Fabricante Prod.");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 220, 120, 42);

        txtFabricante.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtFabricante);
        txtFabricante.setBounds(150, 220, 100, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Valor Compra");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 270, 120, 42);

        txtCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtCompra);
        txtCompra.setBounds(150, 270, 100, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Valor Venda");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel7);
        jLabel7.setBounds(430, 30, 90, 42);

        txtVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtVenda);
        txtVenda.setBounds(530, 30, 110, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("ICMS");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 80, 90, 42);

        txtIcms.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtIcms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIcmsActionPerformed(evt);
            }
        });
        getContentPane().add(txtIcms);
        txtIcms.setBounds(530, 80, 110, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Lucro");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel9);
        jLabel9.setBounds(430, 140, 90, 42);

        txtLucro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtLucro);
        txtLucro.setBounds(530, 140, 110, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Estoque");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 190, 90, 42);

        txtEstoque.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtEstoque);
        txtEstoque.setBounds(530, 190, 110, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Garantia");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel11);
        jLabel11.setBounds(430, 240, 90, 42);

        txtGarantia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtGarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGarantiaActionPerformed(evt);
            }
        });
        getContentPane().add(txtGarantia);
        txtGarantia.setBounds(530, 240, 110, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Tamanho");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel12);
        jLabel12.setBounds(430, 290, 90, 42);

        txtTamanho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtTamanho);
        txtTamanho.setBounds(530, 290, 110, 40);

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(60, 360, 120, 50);

        btnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAlterar.setText("ALTERAR");
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(270, 360, 130, 50);

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(480, 360, 130, 50);

        btnBuscarID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarID.setText("BUSCARID");
        btnBuscarID.setAlignmentY(0.0F);
        btnBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIDActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarID);
        btnBuscarID.setBounds(230, 20, 100, 40);

        btnBuscarNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarNome.setText("BUSNOME");
        btnBuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarNome);
        btnBuscarNome.setBounds(260, 70, 99, 40);

        setBounds(0, 0, 701, 498);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIcmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIcmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIcmsActionPerformed

    private void txtGarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGarantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGarantiaActionPerformed

    private void btnBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIDActionPerformed
        // TODO add your handling code here:
        
        Calcado cal =Crud.buscarCalcado(Integer.parseInt(txtID.getText()));
        
        if(cal!=null){
            
            txtID.setText(String.valueOf(cal.getId()));
            txtNome.setText(cal.getNome());        
            txtModelo.setText(cal.getModelo());
            txtCor.setText(cal.getCor());
            txtFabricante.setText(cal.getFabricante());
            txtCompra.setText(String.valueOf(cal.getValorCompra()));
            txtVenda.setText(String.valueOf(cal.getValorVenda()));
            txtIcms.setText(String.valueOf(cal.getIcms()));
            txtLucro.setText(String.valueOf(cal.getLucro()));
            txtEstoque.setText(String.valueOf(cal.getEstoque()));
            txtGarantia.setText(String.valueOf(cal.getGarantia()));
            txtTamanho.setText(String.valueOf(cal.getTamanho()));
 
        }else{
        
        
            txtID.setText(txtID.getText());
            txtNome.setText("");        
            txtModelo.setText("");
            txtCor.setText("");
            txtFabricante.setText("");
            txtCompra.setText("");
            txtVenda.setText("");
            txtIcms.setText("");
            txtLucro.setText("");
            txtEstoque.setText("");
            txtGarantia.setText("");
            txtTamanho.setText("");
 
        
        }
        

        
  //FIMCLASSE
    }//GEN-LAST:event_btnBuscarIDActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       

            Calcado calcado=new Calcado(Integer.parseInt(txtID.getText()),
                    txtNome.getText(),txtModelo.getText(),
                    txtCor.getText(),txtFabricante.getText(),
                    Double.parseDouble(txtCompra.getText()),
                    Double.parseDouble(txtVenda.getText()),
                    Double.parseDouble(txtIcms.getText()),
                    Double.parseDouble(txtLucro.getText()),
                    Integer.parseInt(txtEstoque.getText()),
                    Integer.parseInt(txtGarantia.getText()),
                    Integer.parseInt(txtTamanho.getText()));
        
        Crud.inserir(calcado);
        
        

// TODO add your handling code here:




    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnBuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNomeActionPerformed
        // TODO add your handling code here:
        
       
   
        
    }//GEN-LAST:event_btnBuscarNomeActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscarID;
    private javax.swing.JButton btnBuscarNome;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCompra;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIcms;
    private javax.swing.JTextField txtLucro;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTamanho;
    private javax.swing.JTextField txtVenda;
    // End of variables declaration//GEN-END:variables
}
